### ISSUE TITLE
Mice are missing Shadows

### ISSUE THREAD

**Issue by Squareys** [bryantvu/Wonderland-Demo#3]
Hi all,

![image](https://user-images.githubusercontent.com/1889284/192864936-3453aec9-96f8-41a6-9ad4-452e293b0a8e.png)

This can be fixed by enabling `castShadow` in `Views > Resources > Pipelines > (the pipeline used by the mice)`

Best,
Jonathan

**Comment by bryantvu** [comment]
The mouse is using material `Bodd-tx` which appears to be `Phone Opaque Textured` under the materials tab.
![2022-09-28 13_40_37-Window](https://user-images.githubusercontent.com/40374800/192884813-be569ba2-a772-418d-86fa-4a293bc882b6.png)

However, it's still not casting shadows after enabling `castShadow` for this pipeline. Any idea why that would be?
![2022-09-28 13_40_07-Window](https://user-images.githubusercontent.com/40374800/192884960-2c022ef1-4bd8-468c-a93d-b52efdf1f515.png)

**Comment by Squareys** [comment]
Btw, you can unfold the mouse material and see the pipeline directly also! Since materials can have the same name, that is also an easy way to ensure that's the same material you're looking at.

You might need to also remove `ALPHA` and `ALPHA_MASK` features.

**Comment by bryantvu** [comment]
Removing the `ALPHA` and `ALPHA_MASK` features did it. Thanks for the help!
